SellWise/Controllers/SaleController.cs
using Microsoft.AspNetCore.Mvc;
using SellWise.Core.Contracts;
using SellWise.Core.Models.ProductModel;
using SellWise.Core.Models.SaleModel;
using System.Security.Claims;

namespace SellWise.Controllers
{
    public class SaleController : BaseController
    {
        private readonly ISaleService saleService;

        public SaleController(ISaleService saleService)
        {
            this.saleService = saleService;
        }

        [HttpGet]
        public async Task<IActionResult> AllProducts(int saleId)
        {
            IEnumerable<ProductViewModel> products = await this.saleService.ViewAllProducts(saleId);

            return View(products);
        }

        [HttpGet]
        public async Task<IActionResult> MySales()
        {
            string userId = User.Id();

            IEnumerable<SaleViewModel> sales = await this.saleService.MySales(userId);

            return View(sales);
        }

        [HttpGet]
        public async Task<IActionResult> CreateSale()
        {
            string userId = User.Id();

            await this.saleService.CreateSale(userId);

            return RedirectToAction(nameof(MySales));
        }

        [HttpGet]
        public async Task<ActionResult> Sale(int saleId)
        {
            var userId = User.Id();

            SaleViewModel sale = await this.saleService.GetSale(saleId, userId);

            return View(sale);
        }

        [HttpGet]
        public async Task<IActionResult> DeleteSale(int saleId)
        {
            var userId = User.Id();

            await this.saleService.DeleteSale(saleId, userId);
            return RedirectToAction(nameof(MySales));
        }

        [HttpGet]
        public async Task<IActionResult> AddProductToSale(int saleId, int productId)
        {
            string userId = User.Id();

            await this.saleService.AddProductToSale(saleId, productId, userId);

            return RedirectToAction(nameof(Sale), new { saleId });
        }

        [HttpPost]
        public async Task<IActionResult> RemoveProductFromSale(int saleId, int productId)
        {
            string userId = User.Id();

            await this.saleService.RemoveProductFromSale(saleId, productId, userId);

            return RedirectToAction(nameof(Sale), new { saleId });
        }

        [HttpPost]
        public async Task<IActionResult> IncreaseProductQuantity(int saleId, int productId)
        {
            string userId = User.Id();

            await this.saleService.IncreaseProductQuantity(saleId, productId, userId);

            return RedirectToAction(nameof(Sale), new { saleId });
        }

        [HttpPost]
        public async Task<IActionResult> DecreaseProductQuantity(int saleId, int productId)
        {
            string userId = User.Id();

            await this.saleService.DecreaseProductQuantity(saleId, productId, userId);

            return RedirectToAction(nameof(Sale), new { saleId });
        }

        [HttpPost]
        public async Task<IActionResult> AddDiscountToSale(int saleId, int discountPercentage)
        {
            string userId = User.Id();

            await this.saleService.AddDiscount(saleId, discountPercentage, userId);

            return RedirectToAction(nameof(Sale), new { saleId });
        }

        [HttpPost]
        public async Task<IActionResult> RemoveDiscountFromSale(int saleId)
        {
            string userId = User.Id();

            await this.saleService.RemoveDiscountFromSale(saleId, userId);

            return RedirectToAction(nameof(Sale), new { saleId });
        }

        [HttpPost]
        public async Task<IActionResult> FinalizeSale(int saleId)
        {
            string userId = User.Id();

            await this.saleService.FinalizeSale(saleId, userId);

            return RedirectToAction(nameof(MySales));
        }
    }
}

SellWise/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SellWise</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SellWise.styles.css" asp-append-version="true" />
</head>
<body style="background-color: #DBF6FF">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3" style="background-color: #2295F0">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Sale" asp-action="MySales" style="color: #DBF6FF"><b>SellWise</b></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Sale" asp-action="MySales" style="color: #DBF6FF"><b>My Sales</b></a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container" style="color: #8F8F8F">
            SellWise - @DateTime.Now.Year
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SellWise/Views/Shared/_PanelPartial.cshtml
<div class="position-fixed" style="top: 55px; left: 0; bottom: 0; width: 230px;">
    <nav id="sidebarMenu" class="collapse d-lg-block sidebar collapse" style="height: 84vh; background-color: #DBF6FF; border: 0px solid #2295F0; border-bottom: 0px">
        <div class="position-sticky">
            <div class="list-group list-group-flush mx-5 mt-3">
                <a class="nav-link" style="color: #2295F0"><b>Menu</b></a>
                <a class="nav-link" style="color: #757575; font-size: 16px" asp-area="" asp-controller="Sale" asp-action="CreateSale"><input type="hidden" name="category" value="Gaming">Create Sale</a>
                <a class="nav-link" style="color: #757575; font-size: 16px" asp-area="" asp-controller="Sale" asp-action="CreateSale"><input type="hidden" name="category" value="Gaming">View Finished Sales</a>
                <a class="nav-link" style="color: #757575; font-size: 16px" asp-area="" asp-controller="Sale" asp-action="CreateSale"><input type="hidden" name="category" value="Gaming">View Unfinished Sales</a>
                <a class="nav-link" style="color: #757575; font-size: 16px" asp-area="" asp-controller="Sale" asp-action="CreateSale"><input type="hidden" name="category" value="Gaming">Shift Statistics</a>
                <a class="nav-link" style="color: #757575; font-size: 16px" asp-area="" asp-controller="Sale" asp-action="CreateSale"><input type="hidden" name="category" value="Gaming">My Shifts</a>
            </div>
        </div>
    </nav>
</div>